/***********************************************************************/
/*                                                                     */
/*  FILE        :CAccelController.cpp                                  */
/*  DATE        :Jul 12, 2020                                          */
/*  DESCRIPTION :モーター目標速度の加減速を制御するクラス              */
/*                                                                     */
/*  This file is generated by Tatsuya Miyazaki                         */
/*                                                                     */
/***********************************************************************/

#include "CAccelController.hpp"

/***********************************************************************/
/*                         加減速度を制御する                          */
/***********************************************************************/

static const fix CAccelController::acceleration = FLOAT_TO_FIX(ACCELERATION);
static const fix CAccelController::deceleration = FLOAT_TO_FIX(DECELERATION);

CAccelController::CAccelController(uint16_t time) {
  presentVelocity = 0;
  targetVelocity = 0;
  cycleTime = INT_TO_FIX(time) / 1000;
}

CAccelController::~CAccelController() {
  ;
}

// 加速が減速かを判断し、加減速度を返す（加減速なしの場合は0）
fix CAccelController::getAccel(void) {
  if (presentVelocity == targetVelocity) {
    return(0);
  } else if (targetVelocity == 0) {
    return(deceleration);
  } else if (targetVelocity > 0) {
    if (presentVelocity < targetVelocity) {
      return(acceleration);
    } else if (presentVelocity > targetVelocity) {
      return(deceleration);
    }
  } else if (targetVelocity < 0) {
    if (presentVelocity > targetVelocity) {
      return(acceleration);
    } else if (presentVelocity < targetVelocity) {
      return(deceleration);
    }
  }
}

// あらかじめ設定した加速度に応じて速度を徐々に変更する
fix CAccelController::accelSpeed(void) {
  fix accel = getAccel();
  if (presentVelocity < targetVelocity) {
    presentVelocity += FIX_MUL(accel, cycleTime);
    if(presentVelocity > targetVelocity) {
      presentVelocity = targetVelocity;
    }
  } else if (presentVelocity > targetVelocity) {
    presentVelocity -= FIX_MUL(accel, cycleTime);
    if(presentVelocity < targetVelocity) {
      presentVelocity = targetVelocity;
    }
  }
  return(presentVelocity);
}

// 目標速度を設定する
void CAccelController::setTargetVelocity(fix target) {
  targetVelocity = target;
}

// 目標速度を取得する
fix CAccelController::getTargetVelocity(void) {
  return(targetVelocity);
}

// 現在速度を取得する
fix CAccelController::getPresentVelocity(void) {
  return(presentVelocity);
}


