/***********************************************************************/
/*                                                                     */
/*  FILE        :CAccelController.hpp                                  */
/*  DATE        :Jul 12, 2020                                          */
/*  DESCRIPTION :モーター目標速度の加減速を制御するクラス              */
/*                                                                     */
/*  This file is generated by Tatsuya Miyazaki                         */
/*                                                                     */
/***********************************************************************/

#pragma once
#include <Arduino.h>
#include "fix.hpp"

/***********************************************************************/
/*                         加減速度を制御する                          */
/***********************************************************************/

#define ACCELERATION (1.0f)     // 車体加速度[m/s2]
#define DECELERATION (1.0f)     // 車体減速度[m/s2]

class CAccelController
{
public:
  // コンストラクタ(引数は実行周期[ms])
  CAccelController(uint16_t time);
  // デストラクタ 
  ~CAccelController();
  // あらかじめ設定した加速度に応じて速度を徐々に変更する
  fix accelSpeed(void);
  // 目標速度を設定する
  void setTargetVelocity(fix target);
  // 目標速度を取得する
  fix getTargetVelocity(void);
  // 現在速度を取得する
  fix getPresentVelocity(void);

private:
  fix presentVelocity;
  fix targetVelocity;
  static const fix acceleration;
  static const fix deceleration;
  fix cycleTime;                       // 実行周期[ms]
  fix getAccel(void);
};

