/***********************************************************************/
/*                                                                     */
/*  FILE        :CLog.hpp                                              */
/*  DATE        :Aug 13, 2020                                          */
/*  DESCRIPTION :ログ出力クラス                                        */
/*                                                                     */
/*  This file is generated by Tatsuya Miyazaki                         */
/*                                                                     */
/***********************************************************************/

#pragma once

#include <Arduino.h>
#include "CTimer.hpp"

/***********************************************************************/
/*                           ログ出力クラス                            */
/***********************************************************************/

class CLog
{
public:
  enum elog {
    DEBUG,
    INFO,
    ERROR,
    WARN
  };
  static void log(enum elog type, String msg) {
    String str = String(CTimer::getGlobalTime());
    str.concat(",");
    if (type == DEBUG) {
      str.concat("DEBUG,");
    } else if (type == INFO) {
      str.concat("INFO,");
    } else if (type == ERROR) {
      str.concat("ERROR,");
    } else if (type == WARN) {
      str.concat("WARN,");
    }
    str.concat(msg);
    Serial.println(str);
  }
  static void info(String msg) {
    log(INFO, msg);
  }
  static void debug(String msg) {
    log(DEBUG, msg);
  }
  static void error(String msg) {
    log(ERROR, msg);
  }
  static void warn(String msg) {
    log(WARN, msg);
  }
};

