/***********************************************************************/
/*                                                                     */
/*  FILE        :COdometry.cpp                                         */
/*  DATE        :Jul 11, 2020                                          */
/*  DESCRIPTION :オドメトリ計算クラス                                  */
/*                                                                     */
/*  This file is generated by Tatsuya Miyazaki                         */
/*                                                                     */
/***********************************************************************/

#ifndef _CODOMETRY_HPP__
#define _CODOMETRY_HPP__

#include <Arduino.h>
#include "fix.hpp"

/***********************************************************************/
/*                          オドメトリ計算                             */
/***********************************************************************/

//#define TIRE_DIAMETER     (0.09f)    // タイヤの直径[m]
#define WHEEL_TREAD       (0.115f)   // 車輪間距離[m]

typedef struct my_point {
  fix x;
  fix y;
  fix z;
} myPoint;

typedef struct my_quaternion {
  fix x;
  fix y;
  fix z;
} myQuaternion;

typedef struct my_pose {
  myPoint position;
  myQuaternion orientation;
} myPose;

typedef struct my_vector3 {
  fix x;
  fix y;
  fix z;
} myVector3;

typedef struct my_twist {
  myVector3 linear;
  myVector3 angular;
} myTwist;

class COdometry
{
public:
  myPose pose;
  myTwist twist;
  COdometry();
  ~COdometry();
  static fix twist2velocityR(fix linearX, fix angularZ);
  static fix twist2velocityL(fix linearX, fix angularZ);
private:
  static const fix myWheelTread;   // 車輪間距離[m]
  //static const fix myTireDiameter;
};

#endif  // _CODOMETRY_HPP__
