/***********************************************************************/
/*                                                                     */
/*  FILE        :COdometry.cpp                                         */
/*  DATE        :Jul 11, 2020                                          */
/*  DESCRIPTION :オドメトリ計算クラス                                  */
/*                                                                     */
/*  This file is generated by Tatsuya Miyazaki                         */
/*                                                                     */
/***********************************************************************/

#ifndef _CODOMETRY_CPP__
#define _CODOMETRY_CPP__

#include "COdometry.hpp"

const fix COdometry::myWheelTread = FLOAT_TO_FIX(WHEEL_TREAD);
//const fix COdometry::myTireDiameter = FLOAT_TO_FIX(TIRE_DIAMETER);

COdometry::COdometry() {
  ;
}

COdometry::~COdometry() {
  ;
}

fix COdometry::twist2velocityR(fix linearX, fix angularZ) {
  fix velocity = linearX - FIX_MUL((myWheelTread / 2), angularZ);
  return(velocity);
}

fix COdometry::twist2velocityL(fix linearX, fix angularZ) {
  fix velocity = linearX + FIX_MUL((myWheelTread / 2), angularZ);
  return(velocity);
}

#endif  // _CODOMETRY_CPP__
