/***********************************************************************/
/*                                                                     */
/*  FILE        :CBuzzer.hpp                                           */
/*  DATE        :Jul 05, 2020                                          */
/*  DESCRIPTION :ブザー駆動クラス                                      */
/*                                                                     */
/*  This file is generated by Tatsuya Miyazaki                         */
/*                                                                     */
/***********************************************************************/

#ifndef _CBUZZER_HPP__
#define _CBUZZER_HPP__

#include <Arduino.h>
#include "CTimer.hpp"

/***********************************************************************/
/*                            ブザー関数                               */
/*                          delay()使用禁止！                          */
/***********************************************************************/
/*     PIN設定    */
#define BUZZER_PIN 5         // ブザー出力
// （MIDIのノート番号11～127が使用可能）
#define MIDI_NOTE_MIN   11   // 発音可能なMIDIノート番号の最小値
#define MIDI_NOTE_MAX   127  // 発音可能なMIDIノート番号の最大値
#define PAUSE_NOTE      0xFF // 無音のノート番号
#ifndef MY_NULL
#define MY_NULL (0)
#endif

typedef struct note {
  uint8_t midiNumber;   // MIDIノート番号 (59～109が使用可能)
  uint16_t timeLength;  // 音の長さ[ms]
} noteType;

class CBuzzer
{
public:
  CBuzzer();
  void disableBuzzer(void);
  void enableBuzzer(void);
  void buzzerON(uint8_t noteNum);
  void buzzerOFF(void);
  void startMelody(noteType *melody);
  void stopMelody(void);
  uint8_t driveBuzzer(void);
  uint8_t isMelodyFinished(void);

private:
  static const uint16_t midi_to_ocr3a[];
  uint8_t defaultTCCR3A;
  uint8_t defaultTCCR3B;
  uint8_t lastTCCR3A;
  uint8_t lastTCCR3B;
  uint8_t lastOCR3A;
  uint8_t lastTCNT3;
  uint8_t usingBuzzer;
  //-------------------------------------------------------
  // 説明     : メロディ関係のグローバル変数
  //-------------------------------------------------------
  static noteType nullNote;         // 空の音符
  noteType *presentNote;
  uint8_t melodyStep;
};

extern noteType shotMelody1[];

#endif  // _CBUZZER_HPP__
