/***********************************************************************/
/*                                                                     */
/*  FILE        :CTimer.hpp                                            */
/*  DATE        :Jun 28, 2020                                          */
/*  DESCRIPTION :タイマークラス                                        */
/*                                                                     */
/*  This file is generated by Tatsuya Miyazaki                         */
/*                                                                     */
/***********************************************************************/

#ifndef _CTIMER_HPP__
#define _CTIMER_HPP__

#include <Arduino.h>

/***********************************************************************/
/*                           タイマー関数                              */
/***********************************************************************/

class CTimer
{
public:
  // タイマーをクリアする
  void startTimer(void);
  // タイマー値[ms]を取得する
  uint32_t getTime(void);
  // タイマー値[ms]を取得する
  static uint32_t getGlobalTime(void) {
    return(millis());
  }

private:
  uint32_t tempTimer;  // 1msの割り込みでインクリメントされる変数
};

#endif  // _CTIMER_HPP__
